[package]
name = "truth-table-rs"
version = "0.1.0"
authors = ["SamedhG <gupta.sam@husky.neu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sexp = "1.1.4"
rustyline = "6.3.0"
